---
description: |+
    ## gecko-t/win10-64-azure
    ### production
owner: mcornmesser@mozilla.com
emailOnError: true
providerId: azure
config:
    lifecycle:
        registrationTimeout: 3600
        reregistrationTimeout: 86400
    maxCapacity: 3
    minCapacity: 0
    launchConfigs:
      -
        tags:
            markcovar: empty_var
            workerType: gecko-t-win10-64-azure
            deploymentId: bf9315a
            sourceScript: provisioners/windows/azure/azure-bootstrap.ps1
            sourceRevision: cloud_windows
            sourceRepository: ronin_puppet
            sourceOrganisation: mozilla-platform-ops
        location: eastus
        subnetId: "/subscriptions/dd0d4271-9b26-4c37-a025-1284a43a4385/resourceGroups/rg-east-us-gecko-t/providers/Microsoft.Network/virtualNetworks/vn-east-us-gecko-t/subnets/sn-east-us-gecko-t"
        osProfile:
            windowsConfiguration:
                timeZone: UTC
                enableAutomaticUpdates: false
        workerConfig:
            genericWorker:
                config:
                    tasksDir: Z:\
                    cachesDir: Z:\caches
                    workerType: win10-64-azure
                    workerGroup: rg-east-us-gecko-t
                    wstAudience: cloudopsstage
                    deploymentId: bf9315a
                    downloadsDir: Z:\downloads
                    wstServerURL: https://websocktunnel-stage.taskcluster.nonprod.cloudops.mozgcp.net
                    provisionerId: gecko-t
                    sentryProject: generic-worker
                    disableReboots: false
                    workerLocation: '{"cloud":"azure","region":"eastus","availabilityZone":"eastus"}'
                    cleanUpTaskDirs: true
                    idleTimeoutSecs: 90
                    livelogPortBase: 60098
                    livelogExecutable: C:\generic-worker\livelog.exe
                    numberOfTasksToRun: 0
                    runAfterUserCreation: C:\generic-worker\task-user-init.cmd
                    taskclusterProxyPort: 80
                    runTasksAsCurrentUser: false
                    shutdownMachineOnIdle: false
                    ed25519SigningKeyLocation: C:\generic-worker\ed25519-private.key
                    taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
                    shutdownMachineOnInternalError: true
        storageProfile:
            osDisk:
                osType: Windows
                createOption: FromImage
            dataDisks:
              -
                lun: 0
                diskSizeGB: 30
                managedDisk:
                    storageAccountType: Premium_LRS
                createOption: FromImage
            imageReference:
                id: "/subscriptions/dd0d4271-9b26-4c37-a025-1284a43a4385/resourceGroups/markcoPacker2/providers/Microsoft.Compute/images/MarkcoTestImage2"
        hardwareProfile:
            vmSize: Standard_DS3_v2
        diagnosticsProfile:
            bootDiagnostics:
                enabled: false
        capacityPerInstance: 1
