---
description: |+
    ## gecko-t/win7-32-gpu-azure
    ### production
owner: grenade@mozilla.com
emailOnError: true
providerId: azure
config:
    lifecycle:
        registrationTimeout: 3600
        reregistrationTimeout: 86400
    maxCapacity: 1
    minCapacity: 0
    launchConfigs:
      -
        tags:
            workerType: gecko-t-win7-32-gpu-azure
            deploymentId: 2facf4f
            sourceScript: userdata/rundsc.ps1
            sourceRevision: 2facf4f
            sourceRepository: OpenCloudConfig
            sourceOrganisation: mozilla-releng
        location: eastus
        subnetId: "/subscriptions/dd0d4271-9b26-4c37-a025-1284a43a4385/resourceGroups/rg-east-us-gecko-t/providers/Microsoft.Network/virtualNetworks/vn-east-us-gecko-t/subnets/sn-east-us-gecko-t"
        osProfile:
            windowsConfiguration:
                timeZone: UTC
                provisionVMAgent: true
                enableAutomaticUpdates: true
            allowExtensionOperations: true
        workerConfig:
            genericWorker:
                config:
                    tasksDir: Z:\
                    cachesDir: Z:\caches
                    workerType: win7-32-gpu-azure
                    workerGroup: rg-east-us-gecko-t
                    wstAudience: cloudopsstage
                    deploymentId: f8358c4
                    downloadsDir: Z:\downloads
                    wstServerURL: https://websocktunnel-stage.taskcluster.nonprod.cloudops.mozgcp.net
                    provisionerId: gecko-t
                    sentryProject: generic-worker
                    disableReboots: false
                    workerLocation: '{"cloud":"azure","region":"eastus","availabilityZone":"eastus"}'
                    cleanUpTaskDirs: true
                    idleTimeoutSecs: 90
                    livelogPortBase: 60098
                    livelogExecutable: C:\generic-worker\livelog.exe
                    numberOfTasksToRun: 0
                    runAfterUserCreation: C:\generic-worker\task-user-init.cmd
                    taskclusterProxyPort: 80
                    runTasksAsCurrentUser: false
                    shutdownMachineOnIdle: false
                    ed25519SigningKeyLocation: C:\generic-worker\ed25519-private.key
                    taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
                    shutdownMachineOnInternalError: true
        storageProfile:
            osDisk:
                osType: Windows
                caching: ReadWrite
                diskSizeGB: 64
                managedDisk:
                    storageAccountType: StandardSSD_LRS
                createOption: FromImage
            dataDisks:
              -
                lun: 0
                diskSizeGB: 128
                managedDisk:
                    storageAccountType: StandardSSD_LRS
                createOption: Empty
              -
                lun: 1
                diskSizeGB: 128
                managedDisk:
                    storageAccountType: StandardSSD_LRS
                createOption: Empty
            imageReference:
                id: "/subscriptions/dd0d4271-9b26-4c37-a025-1284a43a4385/resourceGroups/rg-east-us-gecko-t/providers/Microsoft.Compute/images/east-us-gecko-t-win7-32-gpu-bf6dfe7-2facf4f"
        hardwareProfile:
            vmSize: Standard_NV6_Promo
        diagnosticsProfile:
            bootDiagnostics:
                enabled: false
        capacityPerInstance: 1
