---
description: |+
    ## gecko-t/win7-32-azure
    ### production
owner: grenade@mozilla.com
emailOnError: true
providerId: azure
config:
    lifecycle:
        registrationTimeout: 3600
        reregistrationTimeout: 86400
    maxCapacity: 1
    minCapacity: 0
    launchConfigs:
      -
        tags:
            workerType: gecko-t-win7-32-azure
            deploymentId: 6cf4056
            sourceScript: userdata/rundsc.ps1
            sourceRevision: 6cf4056
            sourceRepository: OpenCloudConfig
            sourceOrganisation: mozilla-releng
        location: centralus
        subnetId: "/subscriptions/dd0d4271-9b26-4c37-a025-1284a43a4385/resourceGroups/rg-central-us-gecko-t/providers/Microsoft.Network/virtualNetworks/vn-central-us-gecko-t/subnets/sn-central-us-gecko-t"
        osProfile:
            windowsConfiguration:
                timeZone: UTC
                provisionVMAgent: false
                enableAutomaticUpdates: false
            allowExtensionOperations: false
        workerConfig:
            genericWorker:
                config:
                    tasksDir: Z:\
                    cachesDir: Z:\caches
                    workerType: win7-32-azure
                    workerGroup: rg-central-us-gecko-t
                    wstAudience: cloudopsstage
                    deploymentId: f8358c4
                    downloadsDir: Z:\downloads
                    wstServerURL: https://websocktunnel-stage.taskcluster.nonprod.cloudops.mozgcp.net
                    provisionerId: gecko-t
                    sentryProject: generic-worker
                    disableReboots: false
                    workerLocation: '{"cloud":"azure","region":"centralus","availabilityZone":"centralus"}'
                    cleanUpTaskDirs: true
                    idleTimeoutSecs: 90
                    livelogExecutable: C:\generic-worker\livelog.exe
                    numberOfTasksToRun: 0
                    runAfterUserCreation: C:\generic-worker\task-user-init.cmd
                    taskclusterProxyPort: 80
                    runTasksAsCurrentUser: false
                    shutdownMachineOnIdle: false
                    ed25519SigningKeyLocation: C:\generic-worker\ed25519-private.key
                    taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
                    shutdownMachineOnInternalError: true
        storageProfile:
            osDisk:
                osType: Windows
                caching: ReadWrite
                diskSizeGB: 64
                managedDisk:
                    storageAccountType: StandardSSD_LRS
                createOption: FromImage
            dataDisks:
              -
                lun: 0
                diskSizeGB: 128
                managedDisk:
                    storageAccountType: StandardSSD_LRS
                createOption: Empty
              -
                lun: 1
                diskSizeGB: 128
                managedDisk:
                    storageAccountType: StandardSSD_LRS
                createOption: Empty
            imageReference:
                id: "/subscriptions/dd0d4271-9b26-4c37-a025-1284a43a4385/resourceGroups/rg-central-us-gecko-t/providers/Microsoft.Compute/images/central-us-gecko-t-win7-32-dc5fd86-6cf4056"
        hardwareProfile:
            vmSize: Standard_F2s_v2
        diagnosticsProfile:
            bootDiagnostics:
                enabled: true
                storageUri: http://geckotdiag.blob.core.windows.net
        capacityPerInstance: 1
      -
        tags:
            workerType: gecko-t-win7-32-azure
            deploymentId: 6cf4056
            sourceScript: userdata/rundsc.ps1
            sourceRevision: 6cf4056
            sourceRepository: OpenCloudConfig
            sourceOrganisation: mozilla-releng
        location: eastus
        subnetId: "/subscriptions/dd0d4271-9b26-4c37-a025-1284a43a4385/resourceGroups/rg-east-us-gecko-t/providers/Microsoft.Network/virtualNetworks/vn-east-us-gecko-t/subnets/sn-east-us-gecko-t"
        osProfile:
            windowsConfiguration:
                timeZone: UTC
                provisionVMAgent: false
                enableAutomaticUpdates: false
            allowExtensionOperations: false
        workerConfig:
            genericWorker:
                config:
                    tasksDir: Z:\
                    cachesDir: Z:\caches
                    workerType: win7-32-azure
                    workerGroup: rg-east-us-gecko-t
                    wstAudience: cloudopsstage
                    deploymentId: f8358c4
                    downloadsDir: Z:\downloads
                    wstServerURL: https://websocktunnel-stage.taskcluster.nonprod.cloudops.mozgcp.net
                    provisionerId: gecko-t
                    sentryProject: generic-worker
                    disableReboots: false
                    workerLocation: '{"cloud":"azure","region":"eastus","availabilityZone":"eastus"}'
                    cleanUpTaskDirs: true
                    idleTimeoutSecs: 90
                    livelogExecutable: C:\generic-worker\livelog.exe
                    numberOfTasksToRun: 0
                    runAfterUserCreation: C:\generic-worker\task-user-init.cmd
                    taskclusterProxyPort: 80
                    runTasksAsCurrentUser: false
                    shutdownMachineOnIdle: false
                    ed25519SigningKeyLocation: C:\generic-worker\ed25519-private.key
                    taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
                    shutdownMachineOnInternalError: true
        storageProfile:
            osDisk:
                osType: Windows
                caching: ReadWrite
                diskSizeGB: 64
                managedDisk:
                    storageAccountType: StandardSSD_LRS
                createOption: FromImage
            dataDisks:
              -
                lun: 0
                diskSizeGB: 128
                managedDisk:
                    storageAccountType: StandardSSD_LRS
                createOption: Empty
              -
                lun: 1
                diskSizeGB: 128
                managedDisk:
                    storageAccountType: StandardSSD_LRS
                createOption: Empty
            imageReference:
                id: "/subscriptions/dd0d4271-9b26-4c37-a025-1284a43a4385/resourceGroups/rg-east-us-gecko-t/providers/Microsoft.Compute/images/east-us-gecko-t-win7-32-dc5fd86-6cf4056"
        hardwareProfile:
            vmSize: Standard_F2s_v2
        diagnosticsProfile:
            bootDiagnostics:
                enabled: true
                storageUri: http://geckotdiag.blob.core.windows.net
        capacityPerInstance: 1
      -
        tags:
            workerType: gecko-t-win7-32-azure
            deploymentId: 6cf4056
            sourceScript: userdata/rundsc.ps1
            sourceRevision: 6cf4056
            sourceRepository: OpenCloudConfig
            sourceOrganisation: mozilla-releng
        location: eastus2
        subnetId: "/subscriptions/dd0d4271-9b26-4c37-a025-1284a43a4385/resourceGroups/rg-east-us-2-gecko-t/providers/Microsoft.Network/virtualNetworks/vn-east-us-2-gecko-t/subnets/sn-east-us-2-gecko-t"
        osProfile:
            windowsConfiguration:
                timeZone: UTC
                provisionVMAgent: false
                enableAutomaticUpdates: false
            allowExtensionOperations: false
        workerConfig:
            genericWorker:
                config:
                    tasksDir: Z:\
                    cachesDir: Z:\caches
                    workerType: win7-32-azure
                    workerGroup: rg-east-us-2-gecko-t
                    wstAudience: cloudopsstage
                    deploymentId: f8358c4
                    downloadsDir: Z:\downloads
                    wstServerURL: https://websocktunnel-stage.taskcluster.nonprod.cloudops.mozgcp.net
                    provisionerId: gecko-t
                    sentryProject: generic-worker
                    disableReboots: false
                    workerLocation: '{"cloud":"azure","region":"eastus2","availabilityZone":"eastus2"}'
                    cleanUpTaskDirs: true
                    idleTimeoutSecs: 90
                    livelogExecutable: C:\generic-worker\livelog.exe
                    numberOfTasksToRun: 0
                    runAfterUserCreation: C:\generic-worker\task-user-init.cmd
                    taskclusterProxyPort: 80
                    runTasksAsCurrentUser: false
                    shutdownMachineOnIdle: false
                    ed25519SigningKeyLocation: C:\generic-worker\ed25519-private.key
                    taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
                    shutdownMachineOnInternalError: true
        storageProfile:
            osDisk:
                osType: Windows
                caching: ReadWrite
                diskSizeGB: 64
                managedDisk:
                    storageAccountType: StandardSSD_LRS
                createOption: FromImage
            dataDisks:
              -
                lun: 0
                diskSizeGB: 128
                managedDisk:
                    storageAccountType: StandardSSD_LRS
                createOption: Empty
              -
                lun: 1
                diskSizeGB: 128
                managedDisk:
                    storageAccountType: StandardSSD_LRS
                createOption: Empty
            imageReference:
                id: "/subscriptions/dd0d4271-9b26-4c37-a025-1284a43a4385/resourceGroups/rg-east-us-2-gecko-t/providers/Microsoft.Compute/images/east-us-2-gecko-t-win7-32-dc5fd86-6cf4056"
        hardwareProfile:
            vmSize: Standard_F2s_v2
        diagnosticsProfile:
            bootDiagnostics:
                enabled: true
                storageUri: http://geckotdiag.blob.core.windows.net
        capacityPerInstance: 1
      -
        tags:
            workerType: gecko-t-win7-32-azure
            deploymentId: 6cf4056
            sourceScript: userdata/rundsc.ps1
            sourceRevision: 6cf4056
            sourceRepository: OpenCloudConfig
            sourceOrganisation: mozilla-releng
        location: northcentralus
        subnetId: "/subscriptions/dd0d4271-9b26-4c37-a025-1284a43a4385/resourceGroups/rg-north-central-us-gecko-t/providers/Microsoft.Network/virtualNetworks/vn-north-central-us-gecko-t/subnets/sn-north-central-us-gecko-t"
        osProfile:
            windowsConfiguration:
                timeZone: UTC
                provisionVMAgent: false
                enableAutomaticUpdates: false
            allowExtensionOperations: false
        workerConfig:
            genericWorker:
                config:
                    tasksDir: Z:\
                    cachesDir: Z:\caches
                    workerType: win7-32-azure
                    workerGroup: rg-north-central-us-gecko-t
                    wstAudience: cloudopsstage
                    deploymentId: f8358c4
                    downloadsDir: Z:\downloads
                    wstServerURL: https://websocktunnel-stage.taskcluster.nonprod.cloudops.mozgcp.net
                    provisionerId: gecko-t
                    sentryProject: generic-worker
                    disableReboots: false
                    workerLocation: '{"cloud":"azure","region":"northcentralus","availabilityZone":"northcentralus"}'
                    cleanUpTaskDirs: true
                    idleTimeoutSecs: 90
                    livelogExecutable: C:\generic-worker\livelog.exe
                    numberOfTasksToRun: 0
                    runAfterUserCreation: C:\generic-worker\task-user-init.cmd
                    taskclusterProxyPort: 80
                    runTasksAsCurrentUser: false
                    shutdownMachineOnIdle: false
                    ed25519SigningKeyLocation: C:\generic-worker\ed25519-private.key
                    taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
                    shutdownMachineOnInternalError: true
        storageProfile:
            osDisk:
                osType: Windows
                caching: ReadWrite
                diskSizeGB: 64
                managedDisk:
                    storageAccountType: StandardSSD_LRS
                createOption: FromImage
            dataDisks:
              -
                lun: 0
                diskSizeGB: 128
                managedDisk:
                    storageAccountType: StandardSSD_LRS
                createOption: Empty
              -
                lun: 1
                diskSizeGB: 128
                managedDisk:
                    storageAccountType: StandardSSD_LRS
                createOption: Empty
            imageReference:
                id: "/subscriptions/dd0d4271-9b26-4c37-a025-1284a43a4385/resourceGroups/rg-north-central-us-gecko-t/providers/Microsoft.Compute/images/north-central-us-gecko-t-win7-32-dc5fd86-6cf4056"
        hardwareProfile:
            vmSize: Standard_F2s_v2
        diagnosticsProfile:
            bootDiagnostics:
                enabled: true
                storageUri: http://geckotdiag.blob.core.windows.net
        capacityPerInstance: 1
      -
        tags:
            workerType: gecko-t-win7-32-azure
            deploymentId: 6cf4056
            sourceScript: userdata/rundsc.ps1
            sourceRevision: 6cf4056
            sourceRepository: OpenCloudConfig
            sourceOrganisation: mozilla-releng
        location: southcentralus
        subnetId: "/subscriptions/dd0d4271-9b26-4c37-a025-1284a43a4385/resourceGroups/rg-south-central-us-gecko-t/providers/Microsoft.Network/virtualNetworks/vn-south-central-us-gecko-t/subnets/sn-south-central-us-gecko-t"
        osProfile:
            windowsConfiguration:
                timeZone: UTC
                provisionVMAgent: false
                enableAutomaticUpdates: false
            allowExtensionOperations: false
        workerConfig:
            genericWorker:
                config:
                    tasksDir: Z:\
                    cachesDir: Z:\caches
                    workerType: win7-32-azure
                    workerGroup: rg-south-central-us-gecko-t
                    wstAudience: cloudopsstage
                    deploymentId: f8358c4
                    downloadsDir: Z:\downloads
                    wstServerURL: https://websocktunnel-stage.taskcluster.nonprod.cloudops.mozgcp.net
                    provisionerId: gecko-t
                    sentryProject: generic-worker
                    disableReboots: false
                    workerLocation: '{"cloud":"azure","region":"southcentralus","availabilityZone":"southcentralus"}'
                    cleanUpTaskDirs: true
                    idleTimeoutSecs: 90
                    livelogExecutable: C:\generic-worker\livelog.exe
                    numberOfTasksToRun: 0
                    runAfterUserCreation: C:\generic-worker\task-user-init.cmd
                    taskclusterProxyPort: 80
                    runTasksAsCurrentUser: false
                    shutdownMachineOnIdle: false
                    ed25519SigningKeyLocation: C:\generic-worker\ed25519-private.key
                    taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
                    shutdownMachineOnInternalError: true
        storageProfile:
            osDisk:
                osType: Windows
                caching: ReadWrite
                diskSizeGB: 64
                managedDisk:
                    storageAccountType: StandardSSD_LRS
                createOption: FromImage
            dataDisks:
              -
                lun: 0
                diskSizeGB: 128
                managedDisk:
                    storageAccountType: StandardSSD_LRS
                createOption: Empty
              -
                lun: 1
                diskSizeGB: 128
                managedDisk:
                    storageAccountType: StandardSSD_LRS
                createOption: Empty
            imageReference:
                id: "/subscriptions/dd0d4271-9b26-4c37-a025-1284a43a4385/resourceGroups/rg-south-central-us-gecko-t/providers/Microsoft.Compute/images/south-central-us-gecko-t-win7-32-dc5fd86-6cf4056"
        hardwareProfile:
            vmSize: Standard_F2s_v2
        diagnosticsProfile:
            bootDiagnostics:
                enabled: true
                storageUri: http://geckotdiag.blob.core.windows.net
        capacityPerInstance: 1
