---
description:  |+
    ## repo:github.com/mozilla-platform-ops/cloud-image-deploy:branch:main
    ### staging

    this role is used by [cloud-image-deploy](https://github.com/mozilla-platform-ops/cloud-image-deploy) to deploy taskcluster windows worker cloud machine images.
scopes:
    - auth:create-role:worker-pool:gecko-1/b-win*
    - auth:create-role:worker-pool:gecko-1/win*
    - auth:create-role:worker-pool:gecko-3/b-win*
    - auth:create-role:worker-pool:gecko-3/win*
    - auth:create-role:worker-pool:gecko-t/t-win*
    - auth:create-role:worker-pool:gecko-t/win*
    - auth:sentry:generic-worker
    - auth:update-role:worker-pool:gecko-1/b-win*
    - auth:update-role:worker-pool:gecko-1/win*
    - auth:update-role:worker-pool:gecko-3/b-win*
    - auth:update-role:worker-pool:gecko-3/win*
    - auth:update-role:worker-pool:gecko-t/t-win*
    - auth:update-role:worker-pool:gecko-t/win*
    - auth:websocktunnel-token:cloudopsstage/*
    - auth:websocktunnel-token:firefoxcitc/*
    - generic-worker:os-group:*
    - generic-worker:run-as-administrator:*
    - queue:create-task:highest:gecko-1/b-win*
    - queue:create-task:highest:gecko-1/win*
    - queue:create-task:highest:gecko-3/b-win*
    - queue:create-task:highest:gecko-3/win*
    - queue:create-task:highest:gecko-t/t-win*
    - queue:create-task:highest:gecko-t/win*
    - queue:create-task:highest:relops*
    - queue:route:index.project.relops.*
    - queue:scheduler-id:taskcluster-github
    - secrets:get:project/relops/image-builder*
    - secrets:get:project/relops/image-deploy*
    - worker-manager:manage-worker-pool:gecko-1/b-win*
    - worker-manager:manage-worker-pool:gecko-1/win*
    - worker-manager:manage-worker-pool:gecko-3/b-win*
    - worker-manager:manage-worker-pool:gecko-3/win*
    - worker-manager:manage-worker-pool:gecko-t/t-win*
    - worker-manager:manage-worker-pool:gecko-t/win*
    - worker-manager:manage-worker-pool:relops*
    - worker-manager:provider:aws
    - worker-manager:provider:az*
