---
description:  |+
    ## repo:github.com/mozilla-platform-ops/cloud-image-builder:branch:main
    ### staging

    this role is used by [cloud-image-builder](https://github.com/mozilla-platform-ops/cloud-image-builder) to build and test taskcluster windows worker cloud machine images.
scopes:
    - generic-worker:os-group:relops-3/win2019/Administrators
    - generic-worker:run-as-administrator:relops-3/*
    - queue:create-task:highest:gecko-1/b-win*
    - queue:create-task:highest:gecko-1/win*
    - queue:create-task:highest:gecko-t/t-win*
    - queue:create-task:highest:gecko-t/win*
    - queue:create-task:highest:relops-3/*
    - queue:route:index.project.relops.cloud-image-builder.*
    - worker-manager:manage-worker-pool:gecko-1/win*
    - worker-manager:manage-worker-pool:gecko-3/win*
    - worker-manager:manage-worker-pool:gecko-t/win*
    - worker-manager:manage-worker-pool:mpd001-1/win*
    - worker-manager:manage-worker-pool:mpd001-3/win*
    - worker-manager:manage-worker-pool:relops*
    - worker-manager:provider:aws
    - worker-manager:provider:az*
    - secrets:get:project/relops/image-builder/dev