---
description: |+
    ## gecko-t/win10-64-azure
    ### production
owner: mcornmesser@mozilla.com
emailOnError: true
providerId: azure
config:
    lifecycle:
        registrationTimeout: 3600
        reregistrationTimeout: 86400
    maxCapacity: 100
    minCapacity: 0
    launchConfigs:
      -
        tags:
            workerType: gecko-t-win10-64-azure
            deploymentId: 03fc422
            sourceScript: provisioners/windows/azure/azure-bootstrap.ps1
            sourceRevision: cloud_windows
            sourceRepository: ronin_puppet
            sourceOrganisation: mozilla-platform-ops
        location: eastus
        subnetId: "/subscriptions/dd0d4271-9b26-4c37-a025-1284a43a4385/resourceGroups/rg-east-us-gecko-t/providers/Microsoft.Network/virtualNetworks/vn-east-us-gecko-t/subnets/sn-east-us-gecko-t"
        osProfile:
            windowsConfiguration:
                timeZone: UTC
                enableAutomaticUpdates: false
        workerConfig:
            genericWorker:
                config:
                    tasksDir: Z:\
                    cachesDir: Z:\caches
                    workerType: win10-64-azure
                    workerGroup: rg-east-us-gecko-t
                    wstAudience: firefoxcitc
                    deploymentId: 03fc422
                    downloadsDir: Z:\downloads
                    wstServerURL: https://firefoxci-websocktunnel.services.mozilla.com
                    provisionerId: gecko-t
                    sentryProject: generic-worker
                    disableReboots: false
                    workerLocation: '{"cloud":"azure","region":"eastus","availabilityZone":"eastus"}'
                    cleanUpTaskDirs: true
                    idleTimeoutSecs: 90
                    livelogPortBase: 60098
                    livelogExecutable: C:\generic-worker\livelog.exe
                    numberOfTasksToRun: 0
                    runAfterUserCreation: C:\generic-worker\task-user-init.cmd
                    taskclusterProxyPort: 80
                    runTasksAsCurrentUser: false
                    shutdownMachineOnIdle: true
                    ed25519SigningKeyLocation: C:\generic-worker\ed25519-private.key
                    taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
                    shutdownMachineOnInternalError: true
        storageProfile:
            osDisk:
                osType: Windows
                createOption: FromImage
            dataDisks:
              -
                lun: 0
                diskSizeGB: 30
                managedDisk:
                    storageAccountType: Standard_LRS
                createOption: FromImage
            imageReference:
                id: "/subscriptions/dd0d4271-9b26-4c37-a025-1284a43a4385/resourceGroups/markcoPacker2/providers/Microsoft.Compute/images/gecko-t-win10-64-azure-eastus-03fc422"
        hardwareProfile:
            vmSize: Standard_DS4
        diagnosticsProfile:
            bootDiagnostics:
                enabled: false
        #priority: Spot
        #evictionPolicy: Deallocate
        #billingProfile:
            #maxPrice: -1
        capacityPerInstance: 1
      -
        tags:
            workerType: gecko-t-win10-64-azure
            deploymentId: 03fc422
            sourceScript: provisioners/windows/azure/azure-bootstrap.ps1
            sourceRevision: cloud_windows
            sourceRepository: ronin_puppet
            sourceOrganisation: mozilla-platform-ops
        location: centralus
        subnetId: "/subscriptions/dd0d4271-9b26-4c37-a025-1284a43a4385/resourceGroups/rg-central-us-gecko-t/providers/Microsoft.Network/virtualNetworks/vn-central-us-gecko-t/subnets/sn-central-us-gecko-t"
        osProfile:
            windowsConfiguration:
                timeZone: UTC
                enableAutomaticUpdates: false
        workerConfig:
            genericWorker:
                config:
                    tasksDir: Z:\
                    cachesDir: Z:\caches
                    workerType: win10-64-azure
                    workerGroup: rg-east-us-gecko-t
                    wstAudience: firefoxcitc
                    deploymentId: 03fc422
                    downloadsDir: Z:\downloads
                    wstServerURL: https://firefoxci-websocktunnel.services.mozilla.com
                    provisionerId: gecko-t
                    sentryProject: generic-worker
                    disableReboots: false
                    workerLocation: '{\"cloud\":\"azure\",\"region\":\"centralus\",\"availabilityZone\":\"centralus\"}'
                    cleanUpTaskDirs: true
                    idleTimeoutSecs: 90
                    livelogPortBase: 60098
                    livelogExecutable: C:\generic-worker\livelog.exe
                    numberOfTasksToRun: 0
                    runAfterUserCreation: C:\generic-worker\task-user-init.cmd
                    taskclusterProxyPort: 80
                    runTasksAsCurrentUser: false
                    shutdownMachineOnIdle: true
                    ed25519SigningKeyLocation: C:\generic-worker\ed25519-private.key
                    taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
                    shutdownMachineOnInternalError: true
        storageProfile:
            osDisk:
                osType: Windows
                createOption: FromImage
            dataDisks:
              -
                lun: 0
                diskSizeGB: 30
                managedDisk:
                    storageAccountType: Standard_LRS
                createOption: FromImage
            imageReference:
                id: "/subscriptions/dd0d4271-9b26-4c37-a025-1284a43a4385/resourceGroups/markcoPacker2/providers/Microsoft.Compute/images/gecko-t-win10-64-azure-centralus-03fc422"
        hardwareProfile:
            vmSize: Standard_DS4
        diagnosticsProfile:
            bootDiagnostics:
                enabled: false
        #priority: Spot
        #evictionPolicy: Deallocate
        #billingProfile:
            #maxPrice: -1
        capacityPerInstance: 1
      -
        tags:
            workerType: gecko-t-win10-64-azure
            deploymentId: 03fc422
            sourceScript: provisioners/windows/azure/azure-bootstrap.ps1
            sourceRevision: cloud_windows
            sourceRepository: ronin_puppet
            sourceOrganisation: mozilla-platform-ops
        location: eastus2
        subnetId: "/subscriptions/dd0d4271-9b26-4c37-a025-1284a43a4385/resourceGroups/rg-east-us-2-gecko-t/providers/Microsoft.Network/virtualNetworks/vn-east-us-2-gecko-t/subnets/sn-east-us-2-gecko-t"
        osProfile:
            windowsConfiguration:
                timeZone: UTC
                enableAutomaticUpdates: false
        workerConfig:
            genericWorker:
                config:
                    tasksDir: Z:\
                    cachesDir: Z:\caches
                    workerType: win10-64-azure
                    workerGroup: rg-east-us-gecko-t
                    wstAudience: firefoxcitc
                    deploymentId: 03fc422
                    downloadsDir: Z:\downloads
                    wstServerURL: https://firefoxci-websocktunnel.services.mozilla.com
                    provisionerId: gecko-t
                    sentryProject: generic-worker
                    disableReboots: false
                    workerLocation: '{\"cloud\":\"azure\",\"region\":\"eastus2\",\"availabilityZone\":\"eastus2\"}'
                    cleanUpTaskDirs: true
                    idleTimeoutSecs: 90
                    livelogPortBase: 60098
                    livelogExecutable: C:\generic-worker\livelog.exe
                    numberOfTasksToRun: 0
                    runAfterUserCreation: C:\generic-worker\task-user-init.cmd
                    taskclusterProxyPort: 80
                    runTasksAsCurrentUser: false
                    shutdownMachineOnIdle: true
                    ed25519SigningKeyLocation: C:\generic-worker\ed25519-private.key
                    taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
                    shutdownMachineOnInternalError: true
        storageProfile:
            osDisk:
                osType: Windows
                createOption: FromImage
            dataDisks:
              -
                lun: 0
                diskSizeGB: 30
                managedDisk:
                    storageAccountType: Standard_LRS
                createOption: FromImage
            imageReference:
                id: "/subscriptions/dd0d4271-9b26-4c37-a025-1284a43a4385/resourceGroups/markcoPacker2/providers/Microsoft.Compute/images/gecko-t-win10-64-azure-eastus2-03fc422"
        hardwareProfile:
            vmSize: Standard_DS4
        diagnosticsProfile:
            bootDiagnostics:
                enabled: false
        #priority: Spot
        #evictionPolicy: Deallocate
        #billingProfile:
            #maxPrice: -1
        capacityPerInstance: 1
      -
        tags:
            workerType: gecko-t-win10-64-azure
            deploymentId: 03fc422
            sourceScript: provisioners/windows/azure/azure-bootstrap.ps1
            sourceRevision: cloud_windows
            sourceRepository: ronin_puppet
            sourceOrganisation: mozilla-platform-ops
        location: northcentralus
        subnetId: "/subscriptions/dd0d4271-9b26-4c37-a025-1284a43a4385/resourceGroups/rg-north-central-us-gecko-t/providers/Microsoft.Network/virtualNetworks/vn-north-central-us-gecko-t/subnets/sn-north-central-us-gecko-t"
        osProfile:
            windowsConfiguration:
                timeZone: UTC
                enableAutomaticUpdates: false
        workerConfig:
            genericWorker:
                config:
                    tasksDir: Z:\
                    cachesDir: Z:\caches
                    workerType: win10-64-azure
                    workerGroup: rg-east-us-gecko-t
                    wstAudience: firefoxcitc
                    deploymentId: 03fc422
                    downloadsDir: Z:\downloads
                    wstServerURL: https://firefoxci-websocktunnel.services.mozilla.com
                    provisionerId: gecko-t
                    sentryProject: generic-worker
                    disableReboots: false
                    workerLocation: '{\"cloud\":\"azure\",\"region\":\"eastus2\",\"availabilityZone\":\"eastus2\"}'
                    cleanUpTaskDirs: true
                    idleTimeoutSecs: 90
                    livelogPortBase: 60098
                    livelogExecutable: C:\generic-worker\livelog.exe
                    numberOfTasksToRun: 0
                    runAfterUserCreation: C:\generic-worker\task-user-init.cmd
                    taskclusterProxyPort: 80
                    runTasksAsCurrentUser: false
                    shutdownMachineOnIdle: truw
                    ed25519SigningKeyLocation: C:\generic-worker\ed25519-private.key
                    taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
                    shutdownMachineOnInternalError: true
        storageProfile:
            osDisk:
                osType: Windows
                createOption: FromImage
            dataDisks:
              -
                lun: 0
                diskSizeGB: 30
                managedDisk:
                    storageAccountType: Standard_LRS
                createOption: FromImage
            imageReference:
                id: "/subscriptions/dd0d4271-9b26-4c37-a025-1284a43a4385/resourceGroups/markcoPacker2/providers/Microsoft.Compute/images/gecko-t-win10-64-azure-eastus2-03fc422"
        hardwareProfile:
            vmSize: Standard_DS4
        diagnosticsProfile:
            bootDiagnostics:
                enabled: false
        #priority: Spot
        #evictionPolicy: Deallocate
        #billingProfile:
            #maxPrice: -1
        capacityPerInstance: 1
      -
        tags:
            workerType: gecko-t-win10-64-azure
            deploymentId: 03fc422
            sourceScript: provisioners/windows/azure/azure-bootstrap.ps1
            sourceRevision: cloud_windows
            sourceRepository: ronin_puppet
            sourceOrganisation: mozilla-platform-ops
        location: southcentralus
        subnetId: "/subscriptions/dd0d4271-9b26-4c37-a025-1284a43a4385/resourceGroups/rg-south-central-us-gecko-t/providers/Microsoft.Network/virtualNetworks/vn-south-central-us-gecko-t/subnets/sn-south-central-us-gecko-t"
        osProfile:
            windowsConfiguration:
                timeZone: UTC
                enableAutomaticUpdates: false
        workerConfig:
            genericWorker:
                config:
                    tasksDir: Z:\
                    cachesDir: Z:\caches
                    workerType: win10-64-azure
                    workerGroup: rg-east-us-gecko-t
                    wstAudience: firefoxcitc
                    deploymentId: 03fc422
                    downloadsDir: Z:\downloads
                    wstServerURL: https://firefoxci-websocktunnel.services.mozilla.com
                    provisionerId: gecko-t
                    sentryProject: generic-worker
                    disableReboots: false
                    workerLocation: '{\"cloud\":\"azure\",\"region\":\"eastus2\",\"availabilityZone\":\"eastus2\"}'
                    cleanUpTaskDirs: true
                    idleTimeoutSecs: 90
                    livelogPortBase: 60098
                    livelogExecutable: C:\generic-worker\livelog.exe
                    numberOfTasksToRun: 0
                    runAfterUserCreation: C:\generic-worker\task-user-init.cmd
                    taskclusterProxyPort: 80
                    runTasksAsCurrentUser: false
                    shutdownMachineOnIdle: true
                    ed25519SigningKeyLocation: C:\generic-worker\ed25519-private.key
                    taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
                    shutdownMachineOnInternalError: true
        storageProfile:
            osDisk:
                osType: Windows
                createOption: FromImage
            dataDisks:
              -
                lun: 0
                diskSizeGB: 30
                managedDisk:
                    storageAccountType: Standard_LRS
                createOption: FromImage
            imageReference:
                id: "/subscriptions/dd0d4271-9b26-4c37-a025-1284a43a4385/resourceGroups/markcoPacker2/providers/Microsoft.Compute/images/gecko-t-win10-64-azure-southcentralus-03fc422"
        hardwareProfile:
            vmSize: Standard_DS4
        diagnosticsProfile:
            bootDiagnostics:
                enabled: false
        #priority: Spot
        #evictionPolicy: Deallocate
        #billingProfile:
            #maxPrice: -1
        capacityPerInstance: 1

