---
name: cloud-image-deploy
version: "0.0.1"
author: Rob Thijssen <rthijssen@gmail.com>
about: minion manager
args:
    - taskcluster-root-url:
        global: true
        short: r
        long: taskcluster-root-url
        env: TASKCLUSTER_ROOT_URL
        help: |+
            the root url of the taskcluster deployment.
            for example:
            * https://community-tc.services.mozilla.com
            * https://firefox-ci-tc.services.mozilla.com
            * https://stage.taskcluster.nonprod.cloudops.mozgcp.net
        takes_value: true
        default_value: https://community-tc.services.mozilla.com
    - client-pattern:
        global: true
        short: c
        long: client-pattern
        help: a regular expression to filter clients by
        takes_value: true
        default_value: \z.
    - role-pattern:
        global: true
        short: l
        long: role-pattern
        help: a regular expression to filter roles by
        takes_value: true
        default_value: \z.
    - workerPool-pattern:
        global: true
        short: w
        long: worker-pool-pattern
        help: a regular expression to filter worker pools by
        takes_value: true
        default_value: \z.
    - deploy-folder:
        global: true
        short: d
        long: deploy-folder
        help: folder path to write deploy configurations
        takes_value: true
        default_value: .deploy
    - snapshot-folder:
        global: true
        short: s
        long: snapshot-folder
        help: folder path to read snapshot configurations
        takes_value: true
        default_value: .snapshot
subcommands:
    - snapshot:
        about: observes and snapshots deployed taskcluster configuration
    - deploy:
        about: deploys taskcluster configurations
    - mutate:
        about: modifies taskcluster worker pool configurations with altered amis
        args:
            - build-sha:
                short: b
                long: build-sha
                help: build sha to obtain ami and deployment ids from
                takes_value: true
                default_value: latest