---
production:
    client:
        - project/relops/image-builder/dev
    role:
        - repo:github.com/mozilla-platform-ops/cloud-image-builder:branch:main
        - repo:github.com/mozilla-platform-ops/cloud-image-deploy:branch:main
        - worker-pool:relops-3/decision
    pool:
        gecko-t:
            - win7-32-azure
staging:
    client:
        - project/relops/image-builder/dev
    role:
        - repo:github.com/mozilla-platform-ops/cloud-image-builder:branch:main
        - repo:github.com/mozilla-platform-ops/cloud-image-deploy:branch:main
        - worker-pool:relops-3/decision
    pool:
        gecko-t:
            - win7-32-azure
