---
staging:
    client:
        - project/relops/image-builder/dev
        - project/relops/image-deploy/dev
    pool:
        gecko-t:
            - win10-64-gpu-azure
            - win7-32-azure
            - win7-32-gpu-azure
