---
staging:
    client:
        - project/relops/image-builder/dev
        - project/relops/image-deploy/dev
    role:
        - repo:github.com/mozilla-platform-ops/cloud-image-builder:branch:master
    pool:
        gecko-t:
            - win10-64-gpu-azure
            - win7-32-azure
            - win7-32-gpu-azure
