production:
  rootUrl: https://firefox-ci-tc.services.mozilla.com
  credentials:
    clientId: username-dev
    accessToken: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
staging:
  rootUrl: https://stage.taskcluster.nonprod.cloudops.mozgcp.net
  credentials:
    clientId: username-dev
    accessToken: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
