---
deleteOnExpiration: false
description: |+
    ## project/relops/image-deploy/dev
    ### staging

    this client is used by [cloud-image-deploy](https://github.com/mozilla-platform-ops/cloud-image-deploy) to deploy taskcluster windows worker pool configurations.
expires: 2022-12-12T23:59:59Z
scopes:
  - worker-manager:manage-worker-pool:gecko-1/win*
  - worker-manager:manage-worker-pool:gecko-3/win*
  - worker-manager:manage-worker-pool:gecko-t/win*
  - worker-manager:provider:azure
